import type { Copy } from './copy';

/** Widen the `as const` literal leaves of Copy to plain primitives, deep-partial, arrays replaced whole. */
type Translatable<T> =
  T extends string ? string :
  T extends number ? number :
  T extends boolean ? boolean :
  T extends readonly (infer U)[] ? readonly Translatable<U>[] :
  T extends object ? { [K in keyof T]?: Translatable<T[K]> } :
  T;

/** English overrides. Untranslated keys fall back to French (see i18n.tsx). Translate in passes. */
export const en: Translatable<Copy> = {
  tabs: {
    home: 'Home',
    sessions: 'Sessions',
    available: 'Available',
    profile: 'Profile',
    progress: 'Progress',
    earnings: 'Earnings',
  },
  header: {
    date: 'Tue · Jun 9',
    greeting: 'Hi, Karim',
    notificationsA11y: 'Notifications, 2 unread',
    profileA11y: "Karim's profile",
    levelA11y: 'Your tier and progression',
    levelTitle: 'Your tier',
    streakLabel: 'Streak',
    residentsLabel: 'Residents',
  },
  reportBanner: {
    title: 'Report to complete',
    subtitle: "Yesterday's session · Bellevue care home",
    action: 'Complete',
  },
  availabilityBanner: {
    title: 'Confirm your availability',
    subtitle: 'Last updated 3 weeks ago. Stay available.',
    action: 'Update',
    a11y: 'Confirm your availability. Last updated 3 weeks ago.',
  },
  nextSession: {
    eyebrow: 'Next session',
    status: 'Confirmed',
    place: 'Les Tilleuls care home',
    address: '12 rue des Lilas, Lyon 3e · 2.4 km',
    locShort: 'Lyon 3e · ~10 min',
    unit: 'Secure unit · Ground floor',
    unitLabel: 'Unit',
    whenLabel: 'When',
    whereLabel: 'Where',
    contactLabel: 'Contact',
    callLabel: 'Call',
    contact: 'Ask for Marie Laurent · Coordinator',
    checkin: "Check-in open. You're on site.",
    checkInCta: "I'm on site",
    directions: 'Directions',
    inPrefix: 'in',
    minUnit: 'min',
    inProgress: 'In progress',
    travel: '~10 min · by car',
    opensLine: 'Check-in opens at 2:15pm',
    awayLine: 'Get closer to check in',
    statusLate: 'Late',
    checkedInLate: 'Checked in · late',
    detailEyebrow: 'Confirmed · Today',
    start: '2:30pm',
    end: '3:30pm',
    duration: '1 hr',
    whenPrefix: 'Today',
    handover: {
      label: 'Handover note',
      meta: 'Sophie Marchand · previous coach · 28 May',
      text: 'Mr Lambert prefers seated exercises due to a knee problem. Keep the warm-up short; the group responds well to music.',
    },
    closeA11y: 'Close session details',
  },
  score: {
    title: 'Coach score',
    outOf: '/ 100',
    equity: 'Equity',
    reputation: 'Reputation',
    proximity: 'Proximity',
    caption: 'Algorithm assignment criteria.',
    a11y: 'Coach score',
  },
  week: {
    eyebrow: 'This week',
    monthEyebrow: 'This month',
    lastWeek: 'Last week',
    nextWeek: 'Next week',
    weekOf: 'Week of',
    prevWeekA11y: 'Previous week',
    nextWeekA11y: 'Next week',
    prevMonthA11y: 'Previous month',
    nextMonthA11y: 'Next month',
    link: 'Sessions',
    seg: { week: 'Week', month: 'Month' },
    toggleA11y: 'Calendar view',
    viewSheetCloseA11y: 'Close calendar view',
    weekdays: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
    // Client reword: "{done} confirmed session(s) out of {total} scheduled · {hours}".
    summaryConfirmedOne: 'confirmed session',
    summaryConfirmedMany: 'confirmed sessions',
    summaryOf: 'out of',
    summaryScheduledOne: 'scheduled',
    summaryScheduledMany: 'scheduled',
    doneLabel: 'done',
    scheduledLabel: 'scheduled',
    hours: '7 hr 30',
    monthHours: '31 hr',
    ofLabel: 'of',
    progressA11y: 'sessions done this week',
    monthProgressA11y: 'sessions done this month',
    tiles: {
      scheduled: 'Scheduled',
      done: 'Done',
      unit: 'sessions',
      complete: 'completed',
    },
    daySection: {
      empty: 'No sessions on this day',
      due: 'Due',
      upcoming: 'Upcoming',
      a11ySessions: 'sessions',
      a11yNone: 'no sessions',
    },
  },
  available: {
    eyebrow: 'Available sessions today',
    link: 'See all',
    near: 'Available near you today · Lyon and nearby',
    apply: 'Apply',
    allTitle: 'Available sessions today',
    closeA11y: 'Close available sessions',
  },
  availableScreen: {
    eyebrow: 'Available sessions',
    title: 'Available',
    seg: { list: 'List', week: 'Week' },
    filterA11y: 'Filter available sessions',
    status: { applied: 'Applied' },
    action: {
      apply: 'Raise your hand',
      withdraw: 'Withdraw',
    },
    toast: {
      applied: 'Your application has been sent',
      withdrawn: 'Your application has been cancelled',
    },
    type: { first: 'First visit', regular: 'Regular session' },
    typeA11y: 'Session type',
    travel: {
      min: 'min',
      by: 'by',
      car: 'car',
      onFoot: 'on foot',
      detailLabel: 'Travel',
      overLimit: 'Beyond your travel time',
      overLimitBody: 'About {mins} min {mode}, beyond your {max} min limit. You can still raise your hand.',
      overLimitTail: 'beyond your limit',
    },
    appliedNote: "You're shortlisted. DS assigns a single coach.",
    empty: 'No available sessions here right now.',
    emptyHint: 'New ones appear as care homes open them near you.',
    filter: {
      title: 'Filters',
      closeA11y: 'Close filters',
      status: 'Status',
      statusAll: 'All',
      statusOpen: 'To apply',
      statusApplied: 'Applied',
      reset: 'Reset',
      showPrefix: 'Show',
      showSuffix: 'sessions',
      showOne: 'Show 1 session',
      showNone: 'No results',
    },
    emptyFiltered: 'No sessions match your filters.',
    clearFilters: 'Clear filters',
    cal: {
      seg: { week: 'Week', month: 'Month', all: 'All' },
      toggleA11y: 'Calendar view',
      viewSheetCloseA11y: 'Close calendar view',
      thisWeek: 'This week',
      thisMonth: 'This month',
      allTitle: 'All available sessions',
      lastWeek: 'Last week',
      nextWeek: 'Next week',
      weekOf: 'Week of',
      prevWeekA11y: 'Previous week',
      nextWeekA11y: 'Next week',
      tiles: { open: 'Available', applied: 'Applied', unit: 'sessions', unitOne: 'session' },
      dayCountSuffix: 'available',
      dayCountSuffixOne: 'available',
      dayEmpty: 'No available sessions on this day.',
      periodEmpty: 'No sessions scheduled',
      a11ySessions: 'available',
      a11ySessionsOne: 'available',
      a11yNone: 'no available sessions',
      prevMonthA11y: 'Previous month',
      nextMonthA11y: 'Next month',
    },
    list: {
      filterA11y: 'Filter available sessions by category',
      cats: { all: 'All', recommended: 'Recommended', urgent: 'Urgent', available: 'Available' },
      tag: { recommended: 'Recommended', urgent: 'Urgent' },
      urgency: { today: 'Today', tomorrow: 'Tomorrow', inDays: 'In', days: 'days' },
      empty: 'No sessions in this category.',
      count: { period: 'available this month', of: 'of', shown: 'shown' },
    },
    detail: {
      title: 'Session details',
      closeA11y: 'Close session details',
      when: 'When',
      where: 'Where',
      copyA11y: 'Copy address',
      copied: 'Address copied',
      unit: 'Unit',
      access: 'Access',
      contact: 'Contact',
      contextA11y: 'Session context',
    },
  },
  earnings: {
    eyebrow: 'Earnings this month',
    link: 'Earnings',
    earned: 'Earned',
    confirmedSub: '12 confirmed sessions',
    projected: 'Projected',
    expected: 'expected',
    projectedSub: '+6 upcoming',
    goal: 'Goal',
    screen: {
      eyebrow: 'My dashboard',
      title: 'Earnings',
      closeA11y: 'Close earnings',
      prevMonthA11y: 'Previous month',
      nextMonthA11y: 'Next month',
      earnedLabel: 'Earned so far',
      trendSuffix: 'vs',
      projectedLabel: 'projected upcoming',
      expectedLabel: 'expected this month',
      exportPdf: 'Export as PDF',
      exportA11y: 'Export this month as a PDF summary',
      stat: {
        sessions: 'Sessions',
        sessionsUnit: 'completed',
        hours: 'Hours',
        scheduledPrefix: 'of',
        scheduledSuffix: 'scheduled',
        rate: 'Rate',
        rateUnit: 'per hour',
      },
      sessionsTitle: "This month's sessions",
      sessionsNote: 'Earnings update after each completed session',
      notRated: 'Not rated',
      historyTitle: 'Payment history',
      historyNote: 'Activity statement, not an invoice',
      sessionsCountUnit: 'sessions',
      status: {
        paid: 'Paid',
        awaiting: 'Awaiting payment',
        inProgress: 'In progress',
      },
      downloadA11y: 'Download statement',
      invoice: {
        title: 'Submit my invoice',
        note: "Send this month's invoice — a file you received by email or a photo.",
        cta: 'Add my invoice',
        ctaA11y: 'Add my invoice for this month',
        sheetTitle: 'Submit my invoice',
        sheetHelp: 'Import a file (the PDF you received by email) or take a photo of your invoice.',
        sheetCloseA11y: 'Close',
        fromFile: 'Import a file',
        fromPhoto: 'Take a photo',
        fromLibrary: 'Choose a photo',
        submittedTitle: 'Invoice sent',
        via: { file: 'File imported', photo: 'Photo' },
        submittedNote: 'Received by Deuxième Souffle · being processed',
        replace: 'Replace',
        replaceA11y: 'Replace the submitted invoice',
      },
    },
  },
  sessions: {
    eyebrow: 'Your schedule',
    title: 'Sessions',
    seg: { upcoming: 'Confirmed', past: 'Past', applications: 'Applications' },
    status: {
      checkinOpen: 'Check-in open',
      confirmed: 'Confirmed',
      checkedIn: 'Checked in',
      reportDue: 'Report due',
      reportSent: 'Report sent',
      inProgress: 'In progress',
    },
    firstVisit: 'First session',
    action: {
      checkin: "I'm on site",
      directions: 'Directions',
      writeReport: 'Write report',
      viewReport: 'View report',
    },
    emptyPast: 'No past sessions yet.',
    emptyUpcoming: 'No upcoming sessions.',
    emptyUpcomingHint: 'Keep your availability up to date so sessions get offered to you.',
    seeAvailability: 'See my availability',
    expandA11y: 'Show session details',
    collapseA11y: 'Hide session details',
    detail: {
      title: 'Session details',
      closeA11y: 'Close session details',
      when: 'When',
      where: 'Where',
      format: 'Format',
      contact: 'On-site contact',
      phone: 'Phone',
      access: 'Access',
      rate: 'Your hourly rate',
      rateUnit: '€ / hour',
      copyA11y: 'Copy address',
      copied: 'Copied',
      banner: {
        checkin: "It's almost time — check in once you're on site.",
        reportDue: 'This session is over. Send your report so the care home gets your feedback.',
      },
    },
    checkInModal: {
      eyebrow: 'On site',
      title: 'Confirm check-in',
      body: "We use your location to confirm you're at the care home, then we let the team know you've arrived.",
      note: 'Location is checked only at check-in, never tracked in the background.',
      confirm: "I'm on site",
      cancel: 'Not yet',
      closeA11y: 'Close check-in',
      locating: "Confirming you're on site…",
      result: {
        success:  { title: 'Checked in', body: "You're on site. The care home has been notified of your arrival. Have a great session." },
        late:     { title: 'Checked in, late', body: "Your check-in is confirmed, but after the scheduled time. The care home has been notified you're late." },
        tooFar:   { title: "You're not there yet", body: "You're still too far from the care home. Head over and check in when you arrive." },
        tooEarly: { title: 'Check-in not open yet', body: 'Check-in opens shortly before the session starts. Come back a little closer to the time.' },
        denied:   { title: 'Location required', body: "We need your location to confirm you're there. Turn on location access to check in." },
      },
      done: 'Done',
      directions: 'Directions',
      openSettings: 'Open settings',
      demoLabel: 'Preview outcome',
      demo: { success: 'On site', late: 'Late', tooFar: 'Too far', tooEarly: 'Too early', denied: 'No GPS' },
    },
    manage: {
      title: 'Manage this session',
      cancelParticipation: 'Cancel my participation',
      declareAbsence: 'Declare an absence',
      late: 'Report a delay',
      cancelShort: 'Cancel',
      absenceShort: 'Absence',
      lateShort: 'Delay',
      transmissionNotes: 'Handover notes',
      notesAdd: 'Add a note',
    },
    availability: {
      title: 'Availability',
      intro: 'Adjust your slots and travel area — it changes which sessions you’re offered.',
      row: 'Update my availability',
    },
    lateModal: {
      title: 'Running late?',
      help: "Let us know roughly how late you'll be. The care home is notified right away.",
      options: {
        five: 'About 5 minutes',
        ten: 'About 10 minutes',
        fifteen: 'About 15 minutes',
        thirty: '30 minutes or more',
      },
      doneTitle: 'Delay reported',
      doneBody: "The care home has been notified you're running late. Check in as usual when you arrive.",
      closeA11y: 'Close delay report',
    },
    cancelModal: {
      title: 'Cancel this session?',
      intro: "You'll be removed from this session. Here's what that means.",
      free: { label: 'No penalty', detail: "You're cancelling more than 48h before the session starts." },
      late: { label: '−2 confidence-index points', detail: "You're cancelling less than 48h before the session starts." },
      consequences: {
        reopen: 'The session is reopened to available coaches right away.',
        notify: 'The care home is notified immediately.',
        matching: 'Repeated late cancellations weigh on your future offers.',
      },
      confirm: 'Cancel my participation',
      keep: 'Keep the session',
      closeA11y: 'Close',
      doneTitle: 'Session cancelled',
      doneBody: 'The care home has been notified and the session is available again.',
      doneBodyLate: 'The care home has been notified and the session is available again. −2 confidence-index points were applied.',
      doneCta: 'Done',
    },
    cancelFlow: {
      closeA11y: 'Close',
      backA11y: 'Back',
      back: 'Back',
      step: 'Step',
      step1Title: 'Before you cancel…',
      warn: 'Cancelling this session will affect your confidence index and your number of sessions.',
      impactHeading: 'Here is the impact:',
      impact: {
        confidence: 'Confidence index',
        sessions: 'Sessions this month',
        ca: 'Revenue forecast',
        pts: 'pts',
        sessionOne: 'session',
        sessionMany: 'sessions',
      },
      keepCta: 'Actually, I can make it',
      proceedCta: 'I understand, keep going',
      maintain: {
        title: 'You’re keeping your session?',
        body: 'Confirm you’re available for this session. The care home is counting on you.',
        preservedTitle: 'Benefits preserved',
        preservedConfidence: 'Confidence index',
        preservedMaintained: 'kept',
        preservedSession: 'Session counted in your month',
        preservedCa: 'Revenue forecast',
        yes: 'Yes, I’m keeping my session',
        no: 'No, I really must cancel',
      },
      step2Title: 'What’s your reason?',
      reasonIntro: 'Your reason helps the DS team understand the situation and speed up the replacement.',
      reasonSelect: 'Select a reason',
      reasons: {
        emergency: { label: 'Medical or family emergency', hint: 'Proof (medical certificate, hospitalisation…) would avoid the points removal — optional.' },
        accident: { label: 'Accident', hint: 'You can attach a statement or a note from your doctor if you have one — not mandatory.' },
        transport: { label: 'Exceptional transport problem', hint: '' },
        other: { label: 'Another reason', hint: '' },
      },
      proofTitle: 'Proof (optional)',
      proofBody: 'As an independent coach, you’re free. If you have proof (certificate, statement…), send it by email to contact@deuxiemesouffle.fr or by WhatsApp to the DS team — no need to upload it in the app. Valid proof avoids the points removal.',
      continue: 'Continue',
      step3Title: 'Final confirmation',
      willHappenTitle: 'By confirming, here is what happens:',
      willHappen: {
        notifyDs: 'The Deuxième Souffle team is notified immediately',
        notifyEhpad: 'The care home is warned (“coach unavailable, new coach incoming”)',
        replacement: 'The DS team takes charge of finding a replacement',
        penalty: 'Removal of −2 pts on your confidence index (unless valid proof is provided)',
      },
      confirmCheck: 'I confirm that I won’t be able to attend this session, and I accept the impact on my confidence index.',
      abortCta: 'No, actually I can make it',
      confirmCta: 'I confirm the cancellation',
      keptTitle: 'Your session is kept',
      keptBody: 'Nothing changes: same slot, same care home. They’re still counting on you.',
      keptCta: 'Great',
      cancelledTitle: 'Session cancelled',
      cancelledBody: 'The care home is notified and the DS team is finding a replacement.',
      cancelledPenalty: '−2 confidence-index points have been applied.',
      cancelledCta: 'Done',
    },
    absenceModal: {
      title: 'Declare an absence',
      body: "Let the care home know you can't make it. They'll be notified right away and the session reassigned.",
      stepPrefix: 'Step',
      stepOf: 'of',
      steps: { reason: 'Reason', details: 'Message', confirm: 'Confirm' },
      reasonLabel: 'Reason',
      reasons: { illness: 'Illness', emergency: 'Personal emergency', transport: 'Transport problem', other: 'Other' },
      detailsLabel: 'Message to the care home',
      detailsOptional: 'optional',
      detailsHelp: 'Anything useful for the coordinator, sent with the notification.',
      detailsPlaceholder: 'e.g. I could run the session on Thursday instead.',
      summaryReason: 'Reason',
      summaryMessage: 'Message',
      summaryNone: 'No message',
      note: 'Frequent or last-minute absences can affect your reputation score.',
      next: 'Continue',
      back: 'Back',
      confirm: 'Declare absence',
      cancel: 'Keep the session',
      closeA11y: 'Close absence',
    },
    notesModal: {
      title: 'Handover notes',
      body: 'Notes are shared with whoever runs the next session here.',
      empty: 'No notes yet. Add the first one.',
      placeholder: 'e.g. Mr Lambert prefers seated exercises (knee). The group responds well to music.',
      save: 'Save note',
      you: 'You',
      justNow: 'Just now',
      closeA11y: 'Close handover notes',
    },
    reportView: {
      title: 'Session report',
      closeA11y: 'Close report',
      submittedLabel: 'Sent',
      reviewStatus: { pending: 'Awaiting validation', validated: 'Validated', changes: 'Changes requested' },
      reviewNote: {
        pending: 'Sent. Awaiting validation by the team. Billing starts once validated.',
        validated: 'Validated. This session is confirmed and your billing is under way.',
        changes: 'The team requested a change before this report can be validated.',
      },
      coordinatorNone: 'No message',
      dsNone: 'No message',
      nextNone: 'No notes left',
      readyYes: 'Yes',
      readyNo: 'No',
    },
    appStatus: { pending: 'Pending' },
    emptyApplications: 'No active applications.',
    appDetail: {
      title: 'Application',
      closeA11y: 'Close application',
      statusLabel: 'Status',
      when: 'Session',
      where: 'Where',
      format: 'Format',
      contact: 'On-site contact',
      applied: 'Applied on',
      note: {
        pending: "Awaiting the care home's decision. You'll be notified if you're selected for this session.",
      },
      manageTitle: 'Manage application',
      withdraw: 'Withdraw my application',
      withdrawConfirm: {
        title: 'Withdraw this application?',
        body: "You'll be removed from the candidates for this session. You can reapply while it stays available.",
        confirm: 'Withdraw',
        cancel: 'Keep my application',
      },
    },
  },
  blank: {
    title: 'Coming soon',
    body: 'This screen is coming soon.',
    closeA11y: 'Close',
  },
  notifications: {
    title: 'Notifications',
    markAllRead: 'Mark all as read',
    sectionNew: 'New',
    sectionEarlier: 'Earlier',
    empty: "You're all caught up.",
    closeA11y: 'Close notifications',
    actionDone: 'Done',
    doneChipA11y: 'Done',
  },
  profile: {
    eyebrow: 'Your account',
    title: 'Profile',
    closeA11y: 'Close profile',
    editPhotoA11y: 'Change profile photo',
    role: 'Coach APA · Lyon',
    settingsTitle: 'Settings',
    settingsEyebrow: 'Account & app',
    openSettingsA11y: 'Open settings',
    status: { active: 'Active', pending: 'Awaiting validation', rejected: 'Application declined' },
    preferences: {
      eyebrow: 'Preferences',
      language: 'Language',
      a11y: 'Choose the app language',
    },
    availability: {
      eyebrow: 'Availability',
      title: 'My availability',
      manage: 'Availability & travel',
      intro: 'Matching uses your availability and travel area to suggest sessions near you.',
      closeA11y: 'Close my availability',
      updatedPrefix: 'Updated',
      justNow: 'just now',
      dayAgo: 'day',
      daysAgo: 'days',
      staleNudge: 'Keep it current to stay matched with nearby sessions.',
      schedule: 'Weekly schedule',
      travel: 'Max travel time',
      transport: 'Transport',
      departure: 'Departure address',
      // Authorized zones (DT-16 revised) — hand-picked from a preselected département list.
      areas: 'Authorized zones',
      areasNone: 'None selected',
      // Per-slot departure addresses (DT-16).
      perSlot: {
        eyebrow: 'Per-slot addresses',
        hint: 'Leave from a different place on some slots? Add a dedicated address and radius.',
        empty: 'Every slot leaves from your primary address.',
        add: 'Add a per-slot address',
        coverage: 'Slots',
        radius: 'Radius',
        noCoverage: 'No slots selected',
        remove: 'Remove this address',
        slotOne: 'slot',
        slotMany: 'slots',
      },
      fine: {
        eyebrow: 'Precise time-slots',
        hint: 'Refine a half-day into time windows, each with its own zones and travel cap. With no window, the half-day stays fully open.',
        empty: 'No precise slots. Your open half-days are open in full.',
        add: 'Add a precise slot',
        remove: 'Remove this slot',
        allZones: 'All my zones',
        noneOpen: 'Turn on a half-day in the schedule first.',
      },
      unavailability: 'Time off',
      cta: 'Update my availability',
      // Guided flow (mockup "dispos coach v5" screens 2→12). Mirrors the FR `flow` block.
      flow: {
        back: 'Back',
        gauge: 'Session potential',
        hubAddresses: 'Addresses',
        hubZones: 'Favorite zones',
        hubCreneaux: 'Time-slots',
        detailedPill: 'detailed',
        activeSlotsOne: 'half-day active',
        activeSlotsMany: 'half-days active',
        validate: 'Confirm my availability',
        transportTitle: 'Transport & travel',
        transportQ: 'How do you get around?',
        travelDefault: 'Max travel time (default)',
        travelNote: 'This can be adjusted per slot (e.g. between two already-booked sessions).',
        addressTitle: 'Departure addresses',
        addressIntro: 'Where do you leave from to reach our care homes?',
        primaryBadge: 'Default',
        addSecondary: 'Add a different address on some days',
        whyTwoTitle: 'Why two addresses?',
        whyTwoBody: 'Sometimes staying elsewhere during the week (shared custody…)? Tell us so we match the right sessions.',
        secondaryTitle: 'Address by day',
        secondaryIntro: 'Days you leave from another address.',
        secondaryBadge: 'Secondary address',
        activeDays: 'Active days',
        removeSecondary: 'Remove this address',
        street: 'Street',
        postal: 'Postcode',
        city: 'City',
        zonesTitle: 'My zones',
        zonesIntro: 'Tick your départements. You can restrict some zones per slot in the Time-slots step.',
        creneauxTitle: 'My time-slots',
        modeRapide: 'Quick mode',
        modeDetaille: 'Detailed mode',
        rapideHint: 'Tap to turn each half-day on or off.',
        detailleHint: 'Tap an active half-day to refine it into precise slots.',
        amRange: '9 am – 12 pm',
        pmRange: '2 pm – 5 pm',
        legendFine: '🎯 = precise slots defined',
        recapLink: 'Week recap',
        detailedOn: 'Detailed mode on',
        addSlot: 'Add a slot',
        gapTitle: 'Deliberate gap?',
        gapBody: 'Between two slots, matching proposes nothing on that window — deliberate and fine.',
        detailGate: 'Turn this half-day on in quick mode first.',
        slotTitle: 'New slot',
        slotEditTitle: 'Edit slot',
        nextZones: 'Next: allowed zones',
        slotZonesTitle: 'Zones for this slot',
        slotZonesIntro: 'On this slot, I’m available for:',
        allZonesHint: 'default',
        restrictedHint: 'I’ll pick below',
        slotTravelHint: 'Reduced to stay close between sessions.',
        validateSlot: 'Confirm this slot',
        endAfterStart: 'End must come after start.',
        recapTitle: 'My week recap',
        allZonesShort: 'all zones',
        closed: 'Off',
        validationTitle: 'Time off & confirm',
        timeOffIntro: 'Periods when you won’t be available.',
        addPeriod: 'Add a period',
        periodLabel: 'Label',
        periodStart: 'Start',
        periodEnd: 'End',
        periodLabelPh: 'e.g. Summer holiday',
        periodDatePh: 'e.g. 4 Aug 2026',
        removePeriod: 'Remove this period',
        savePeriod: 'Add period',
        finalRecap: 'Final recap',
        confirm: 'Confirm my availability',
        halfDayCount: 'half-day(s)',
        fineDayCount: 'day(s) detailed',
      },
    },
    activity: {
      eyebrow: 'Progression & activity',
      badges: 'Tiers',
      badgesValue: 'Or · 3/5 tiers',
      reports: 'Report history',
      reportsValue: '14 sent',
      feedback: 'Care home reviews',
      feedbackValue: '4.8 average',
    },
    goals: {
      eyebrow: 'Goals',
      target: 'Monthly goal',
      rate: 'Default hourly rate',
    },
    documents: {
      eyebrow: 'My documents',
      note: 'Required to keep your account active',
      cv: 'CV',
      urssaf: 'URSSAF certificate',
      insurance: 'Professional insurance',
      diploma: 'APA diploma',
      status: { verified: 'Verified', pending: 'Pending' },
    },
    account: {
      eyebrow: 'Account',
      personal: 'Personal information',
      calendar: 'Google Calendar',
      connected: 'Connected',
      password: 'Change password',
      deleteAccount: 'Delete account',
      deleteRequested: 'Requested',
    },
    support: {
      eyebrow: 'Help',
      help: 'Help center',
      contact: 'Contact us',
      version: 'Version',
    },
    logout: 'Log out',
    logoutA11y: 'Log out of your account',
    common: { cancel: 'Cancel', save: 'Save', close: 'Close', done: 'Done' },
    avatarSheet: {
      title: 'Profile photo',
      help: 'Add a photo so the care home recognizes you when you arrive.',
      choose: 'Choose a photo',
      remove: 'Remove photo',
      closeA11y: 'Close photo options',
    },
    edit: {
      transport: { title: 'Transport mode', car: 'Car', twoWheel: 'Two-wheeler', velo: 'Bike', transports: 'Public transit', walking: 'On foot', other: 'Other' },
      vehicle: { title: 'Your vehicle', label: 'Vehicle', placeholder: 'e.g. Public transport' },
      travel: {
        title: 'Max travel time',
        help: "How far you're willing to travel, from your departure address.",
        decA11y: 'Decrease max travel time',
        incA11y: 'Increase max travel time',
      },
      schedule: {
        title: 'Weekly schedule',
        help: 'Turn on the half-days when you can work, weekends included.',
        weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        am: 'Morning',
        pm: 'Afternoon',
        notSet: 'No half-days set',
      },
      departure: {
        title: 'Departure address',
        primaryLabel: 'Primary address',
        help: 'Your default starting point. Travel time to each session is calculated from here.',
      },
      point: {
        title: 'Per-slot address',
        addTitle: 'New per-slot address',
        addressLabel: 'Address',
        addressHelp: 'Where you leave from for the chosen slots.',
        coverageTitle: 'Slots covered',
        coverageHelp: 'Tick the half-days that leave from this address.',
        radiusTitle: 'Radius for this address',
      },
      fine: {
        addTitle: 'New precise slot',
        editTitle: 'Edit slot',
        daySection: 'Half-day',
        start: 'Start time',
        end: 'End time',
        selected: 'Selected slot',
        zonesSection: 'Zones allowed for this slot',
        allZones: 'All my zones',
        restricted: 'Restricted zones',
        travel: 'Travel cap for this slot',
        decA11y: 'Decrease travel cap',
        incA11y: 'Increase travel cap',
        closeA11y: 'Close precise slot',
      },
      // Authorized zones picker — multi-select from the preselected département list.
      zones: {
        title: 'Authorized zones',
        help: 'The areas where you want to work as a priority. You can still receive session proposals in other areas (you remain free to accept each one). Matching’s “proximity” criterion will favour these zones.',
        closeA11y: 'Close authorized zones',
      },
      unavailability: { title: 'Time off', label: 'Period', help: 'Holidays or leave. Enter "None upcoming" when you are fully available.' },
      target: { title: 'Monthly goal', label: 'Sessions per month', help: 'Used to share sessions fairly between coaches.', flexibilityLabel: 'Flexibility', strict: 'Strict', flexible: 'Flexible' },
      rate: { title: 'Default hourly rate', label: 'Rate (€ / hour)' },
      personal: { title: 'Personal information', name: 'Full name', email: 'Email', phone: 'Phone' },
    },
    password: {
      title: 'Change password',
      current: 'Current password',
      next: 'New password',
      confirm: 'Confirm new password',
      help: 'At least 8 characters.',
      mismatch: "The new passwords don't match.",
      tooShort: 'Use at least 8 characters.',
      missing: 'Fill in all fields.',
    },
    confirmAvail: {
      title: 'Still available as usual?',
      body: "Matching uses your weekly availability and travel area to suggest sessions. Confirm it's up to date, or review your settings.",
      primary: "Yes, it's up to date",
      secondary: 'Review settings',
    },
    calendar: {
      connectTitle: 'Connect Google Calendar',
      connectBody: 'Automatically sync your confirmed sessions with your Google Calendar.',
      connect: 'Connect',
      disconnectTitle: 'Disconnect Google Calendar?',
      disconnectBody: 'Your confirmed sessions will no longer sync with Google Calendar.',
      disconnect: 'Disconnect',
      disconnected: 'Not connected',
    },
    documentSheet: {
      body: 'This document is saved and keeps your account active.',
      replace: 'Replace document',
      pendingNote: 'New file sent. Awaiting verification by the DS team.',
    },
    logoutConfirm: { title: 'Log out?', body: "You'll need to log back in to see your sessions." },
    deleteConfirm: {
      title: 'Delete your account?',
      body: 'This sends a request to the Deuxième Souffle team. Your account will be deactivated and your personal data removed. Your invoices and activity history are kept for the period required by law (URSSAF, accounting), then deleted.',
      confirm: 'Request deletion',
      requestedTitle: 'Deletion requested',
      requestedBody: "The team has received your request and will confirm by email. You can keep using the app until it's processed.",
    },
    about: { title: 'Deuxième Souffle · Coach', body: 'APA coaching coordination for care homes.\nVersion 0.1.0 (prototype).' },
    links: {
      helpUrl: 'https://deuxiemesouffle.fr/aide',
      contactEmail: 'support@deuxiemesouffle.fr',
      contactSubject: 'Coach app: support request',
    },
  },
  game: {
    eyebrow: 'Progression',
    tierPrefix: 'Tier',
    totalSuffix: 'sessions completed',
    collected: '{n}/{total} collected',
    toNextOne: 'session to',
    toNextN: 'sessions to',
    maxedReadout: 'Top tier',
    maxedCaption: 'Top tier reached',
    closeA11y: 'Close progression',
    nextTierEyebrow: 'Next tier',
    gapOne: 'Almost there',
    gapN: '{n} to go',
    ofTarget: 'of',
    lockedA11y: 'locked',
    collectionTitle: 'Tiers',
    seeAll: 'See all',
    collectionCloseA11y: 'Close tiers',
    earnedTitle: 'Earned',
    lockedTitle: 'To unlock',
    reachedLabel: 'Reached',
    howTitle: 'How you progress',
    how: {
      sessions: { title: 'Complete sessions', desc: 'Every finished session brings the next tier closer.' },
      climb: { title: 'Climb the tiers', desc: 'From Bronze to Diamant: five tiers to unlock.' },
    },
    note: 'Your tiers grow only with completed sessions. The DS team sees them too, but they never affect your pay.',
    // Tier names stay French (the canonical brand naming); descriptions are localised.
    tiers: {
      bronze: { name: 'Bronze', desc: '1 session completed' },
      argent: { name: 'Argent', desc: '25 sessions completed' },
      or: { name: 'Or', desc: '50 sessions completed' },
      platine: { name: 'Platine', desc: '100 sessions completed' },
      diamant: { name: 'Diamant', desc: '200 sessions completed' },
    },
    celebrate: {
      eyebrow: 'Tier unlocked',
      today: 'Reached today',
      subtitle: 'Recognition only — never pay.',
      cta: 'Awesome!',
      announce: 'Tier unlocked:',
    },
  },

  // Onboarding & auth (E01) — English overrides. Community name = "The Movement" (DT-03). The whole
  // tunnel (Splash · Welcome · Login · Forgot · Sign-up · Pending) reads from useCopy(), so these
  // strings replace the French source when the app is set to English.
  auth: {
    splash: {
      wordmark: 'Deuxième Souffle',
      tagline: 'The Movement',
      a11y: 'Deuxième Souffle',
      skipA11y: 'Skip',
    },
    welcome: {
      eyebrow: 'APA coach',
      title: 'Your sessions,\nyour pace.',
      body: 'Get matched with sessions at care homes near you, check in on site and track your earnings — all in one place.',
      login: 'Log in',
      apply: 'Apply as a coach',
      applyA11y: 'Apply to become a coach',
    },
    login: {
      eyebrow: 'Welcome back',
      title: 'Log in',
      subtitle: 'Log in to your coach account.',
      google: 'Continue with Google',
      orDivider: 'or',
      email: { label: 'Email', placeholder: 'you@email.com' },
      password: {
        label: 'Password',
        placeholder: 'Your password',
        showA11y: 'Show password',
        hideA11y: 'Hide password',
      },
      forgot: 'Forgot password?',
      forgotA11y: 'Reset your password',
      forgotSent: 'If this email is registered, we’ll send a reset link.',
      submit: 'Log in',
      error: 'Enter a valid email and your password to continue.',
      backA11y: 'Back',
      noAccount: 'New coach?',
      createAccount: 'Create an account',
    },
    forgot: {
      eyebrow: 'Password help',
      title: 'Reset password',
      subtitle: 'Enter your coach account email and we’ll send a link to set a new password.',
      email: { label: 'Email', placeholder: 'you@email.com' },
      submit: 'Send the link',
      invalid: 'Enter a valid email to continue.',
      backA11y: 'Back to login',
      backToLogin: 'Back to login',
      sentTitle: 'Check your email',
      sentBodyPrefix: 'If ',
      sentBodySuffix: ' is registered, a link to reset your password is on its way. It may take a few minutes to arrive.',
      sentHint: 'Didn’t get it? Check your spam, or resend it.',
      resend: 'Resend',
      done: 'Back to login',
    },
    signup: {
      eyebrow: 'Join The Movement',
      title: 'Apply as a coach',
      subtitle: 'Create your coach account. The team reviews it before you go live.',
      google: 'Continue with Google',
      orDivider: 'or',
      stepLabel: 'Step 1 of 2',
      step: 'Coach identity',
      optionalTag: 'optional',
      civility: {
        label: 'Title',
        placeholder: 'Select',
        sheetTitle: 'Title',
        options: { madam: 'Ms', sir: 'Mr' },
      },
      dob: { label: 'Date of birth', placeholder: 'DD/MM/YYYY' },
      firstName: { label: 'First name', placeholder: 'Marie' },
      lastName: { label: 'Last name', placeholder: 'Dubois' },
      email: { label: 'Email', placeholder: 'marie.dubois@coach.fr' },
      phone: { label: 'Phone', placeholder: '06 12 34 56 78' },
      address: {
        label: 'Home address',
        placeholder: '12 rue de Vaugirard, 75015 Paris',
        help: 'Used to calculate your default travel time.',
      },
      siret: { label: 'SIRET', placeholder: '123 456 789 00012', help: 'Your sole-trader or company number.' },
      legalStatus: {
        label: 'Legal status',
        placeholder: 'Select',
        sheetTitle: 'Legal status',
        options: {
          selfEmployed: 'Self-employed (auto-entrepreneur)',
          soleProprietor: 'Sole proprietorship',
          company: 'Company (EURL / SASU)',
          other: 'Other',
        },
      },
      verification: {
        title: 'Automatic verification',
        body: 'Your SIRET number is checked against INSEE. The Deuxième Souffle training is required before validation.',
      },
      password: {
        label: 'Password',
        placeholder: 'At least 8 characters',
        showA11y: 'Show password',
        hideA11y: 'Hide password',
      },
      invite: { label: 'Invitation code', optional: 'optional', placeholder: 'If the team gave you one' },
      consent: 'I accept the terms of use and the privacy policy.',
      consentA11y: 'Accept the terms of use and the privacy policy',
      submit: 'Send my application',
      submitShort: 'Apply',
      haveAccount: 'Already have an account?',
      login: 'Log in',
      backA11y: 'Back',
      error: 'Check the highlighted fields to send your application.',

      stepTitles: ['Coach identity', 'Your documents', 'Area & availability', 'Rate & preferences'],
      stepOfPrefix: 'Step ',
      stepOfMid: ' of ',
      back: 'Previous',
      cancel: 'Cancel',
      cont: 'Continue',
      kyc: {
        intro: 'Add the documents you already have — you can complete the rest from your space.',
        tagMandatory: 'mandatory',
        tagMandatory6m: 'mandatory · 6 months',
        tagOptional: 'optional',
        statusReceived: 'Received',
        statusWaiting: 'Waiting',
        statusOptional: 'Optional',
        add: 'Add',
        view: 'View',
        renewTitle: 'Certificate of vigilance · 6-month reminder',
        renewBody: 'The system automatically reminds you to provide an up-to-date certificate every 6 months.',
        docs: {
          cv: { label: 'CV', desc: 'Professional background · PDF' },
          diploma: { label: 'APA diploma or equivalent', desc: 'STAPS APA, BPJEPS APT, etc. · PDF' },
          urssaf: { label: 'URSSAF / vigilance certificate', desc: 'Less than 6 months old · PDF' },
          insurance: { label: 'Professional liability insurance', desc: 'Currently valid · PDF' },
          training: { label: 'DS training certificate', desc: 'Deuxième Souffle training completed · PDF' },
          license: { label: 'Driving licence / Navigo pass', desc: 'Depending on your transport · PDF' },
          record: { label: 'Criminal record (B3)', desc: 'Recommended for work with seniors · PDF' },
        },
      },
      area: {
        zonesLabel: 'Preferred intervention areas',
        zonesHelp: 'Areas where you’d like to work first. You can still receive proposals elsewhere.',
        availLabel: 'Weekly availability',
        availHelp: 'Tick the half-days you’re usually available. You can refine this later.',
        days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        slotAm: 'Morning (10–12)',
        slotPm: 'Afternoon (14–17)',
        cellOnA11y: 'available',
        cellOffA11y: 'unavailable',
      },
      tariff: {
        rateLabel: 'Desired hourly rate',
        rateHelp: 'Indicative — the team validates your rate before you go live. Editable later.',
        rateSuffix: '€ excl. tax / h',
        presetJunior: 'junior',
        presetStandard: 'standard',
        presetSenior: 'senior',
        presetCustom: 'Custom',
        targetLabel: 'Desired monthly goal',
        targetSuffix: 'sessions / month',
        targetHelp: 'Indicative — helps us propose the right volume of sessions.',
        caPrefix: '≈ ',
        caSuffix: ' € monthly revenue',
        specialtiesLabel: 'Specialities',
        specialtiesHelp: 'Optional — helps the team assign you to the right units.',
        specialties: {
          classic: 'Standard unit',
          protected: 'Protected unit (UP / UHR)',
          helpers: 'Family carers',
          caregivers: 'Care staff',
          playful: 'Playful activity',
          memory: 'Memory work',
          strength: 'Strength training',
        },
      },
    },
    pending: {
      eyebrow: 'Account status',
      statusChip: 'Pending validation',
      title: 'Application under review',
      bodyPrefix: 'Thanks for your application, ',
      bodySuffix: '. Our team is checking your details and will email you as soon as your account is approved.',
      bodyNoName: 'Thanks for your application. Our team is checking your details and will email you as soon as your account is approved.',
      processingTime: 'Usual review time: 2–3 business days',
      docsEyebrow: 'Required documents',
      docsNote: 'Add any missing ones to speed up your validation.',
      docs: { cv: 'CV', urssaf: 'URSSAF certificate', insurance: 'Professional insurance', diploma: 'APA diploma' },
      docStatusMissing: 'To add',
      docStatusReceived: 'Received',
      complete: 'Complete my application',
      completeBody: 'Uploading your documents is the next step. Your application is saved and the team can already see it.',
      backA11y: 'Back',
      demoApprove: 'Preview: simulate validation',
      upload: {
        title: 'My documents',
        intro: 'Add your supporting documents. The team reviews them as soon as they arrive.',
        formats: 'Accepted formats: PDF, JPG or PNG · 10 MB max.',
        required: 'Required',
        received: 'Received',
        missing: 'To add',
        uploading: 'Uploading…',
        add: 'Add',
        replace: 'Replace',
        remove: 'Remove',
        removeA11y: 'Remove this document',
        pickTitle: 'Add a document',
        pickFile: 'Choose a file',
        pickPhoto: 'Take a photo',
        pickCloseA11y: 'Close document picker',
        closeA11y: 'Close my documents',
        remainingOne: 'document still to add',
        remainingMany: 'documents still to add',
        allIn: 'All your documents are in.',
        done: 'Done',
      },
    },
    verify: {
      eyebrow: 'Last step',
      title: 'Verify your email',
      bodyPrefix: 'We sent a confirmation link to ',
      bodySuffix: '. Open it to finish your application.',
      hint: 'Didn’t get it? Check your spam, or resend the link.',
      confirm: 'I’ve confirmed my email',
      resend: 'Resend the email',
      resent: 'Email resent',
      resendInPrefix: 'Resend in ',
      resendInSuffix: ' s',
      changeEmail: 'Change my email address',
      closeA11y: 'Back to sign-up',
    },
    accepted: {
      eyebrow: 'Welcome to The Movement',
      statusChip: 'Account validated',
      titlePrefix: 'Welcome, ',
      titleSuffix: '!',
      titleNoName: 'You’re one of us!',
      body: 'Your application is approved. Your coach space is ready.',
      highlightsTitle: 'What’s waiting for you',
      highlights: {
        matching: 'Matched sessions near you',
        checkin: 'On-site check-in in one tap',
        revenue: 'Your earnings, all in one place',
      },
      cta: 'Enter my space',
    },
  },
};
